# Generated by Django 5.2 on 2025-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem principal do produto (opcional).', null=True, upload_to='products/images/%Y/%m/%d/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Modelo do Prduto.', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Cor principal do produto ou fragrância (opcional).', max_length=50, verbose_name='Cor ou Fragrância'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(default='', editable=False, help_text='Código único para controle interno (gerado automaticamente).', max_length=20, unique=True, verbose_name='Código Interno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nome do produto.', max_length=100, verbose_name='Nome do Produto'),
        ),
    ]
