# Generated by Django 5.2 on 2025-05-04 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('IND', 'Pessoa Física'), ('CORP', 'Pessoa Jurídica')], default='IND', max_length=6, verbose_name='Tipo de Cliente')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo')),
                ('preferred_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Como gostaria de ser chamado')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('tax_id', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profissão')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='Interesses')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-registration_date', 'full_name'],
                'indexes': [models.Index(fields=['full_name'], name='customers_c_full_na_70c97a_idx'), models.Index(fields=['tax_id'], name='customers_c_tax_id_c2c068_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx')],
            },
        ),
    ]
