# Generated by Django 5.2 on 2025-04-20 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11,14}$')], verbose_name='CPF/CNPJ'),
        ),
    ]
