# Generated by Django 5.2 on 2025-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo / Razão Social'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido / Nome Fantasia'),
        ),
    ]
