# Generated by Django 5.2 on 2025-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_full_name_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('IND', 'Pessoa Física'), ('CORP', 'Pessoa Jurídica')], default='IND', max_length=6, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
