# Generated by Django 5.2 on 2025-05-15 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_full_name_alter_customer_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve ter 10 ou 11 dígitos.')], verbose_name='Telefone'),
        ),
    ]
