# Generated by Django 5.2 on 2025-04-20 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantidade atual disponível em estoque', verbose_name='Quantidade Disponível')),
                ('min_quantity', models.PositiveIntegerField(default=5, help_text='Quantidade mínima para gerar alertas de reposição', verbose_name='Estoque Mínimo')),
                ('location', models.CharField(blank=True, help_text='Corredor, prateleira ou código de localização', max_length=50, verbose_name='Localização no Armazém')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do estoque', verbose_name='Última Atualização')),
                ('product', models.OneToOneField(help_text='Produto relacionado a este registro de estoque', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['product'], name='stock_product_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('RETURN', 'Devolução'), ('ADJUSTMENT', 'Ajuste'), ('CANCELLATION', 'Cancelamento')], help_text='Tipo de operação realizada no estoque', max_length=12, verbose_name='Tipo de Movimentação')),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade movimentada (valor sempre positivo)', verbose_name='Quantidade')),
                ('reference_id', models.CharField(blank=True, help_text='Identificador externo para rastreamento (ex: número do pedido, NF, etc.)', max_length=50, verbose_name='ID de Referência')),
                ('notes', models.TextField(blank=True, help_text='Informações adicionais sobre a movimentação', verbose_name='Observações')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Indica se esta movimentação foi cancelada', verbose_name='Cancelado')),
                ('cancelled_reason', models.TextField(blank=True, help_text='Descrição detalhada do motivo do cancelamento', verbose_name='Motivo do Cancelamento')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Data e hora em que o cancelamento foi realizado', null=True, verbose_name='Data de Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Última Atualização')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Usuário que realizou o cancelamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_movements', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('product', models.ForeignKey(help_text='Produto que foi movimentado no estoque', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(help_text='Usuário que registrou a movimentação', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='movement_product_idx'), models.Index(fields=['movement_type'], name='movement_type_idx'), models.Index(fields=['is_cancelled'], name='movement_cancelled_idx')],
            },
        ),
    ]
