# Generated by Django 5.2 on 2025-05-04 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, help_text='Rua, Avenida, Travessa, etc.', max_length=100, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, help_text="Número ou 'SN' se não houver", max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, help_text='Apartamento, Bloco, etc.', max_length=50, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=50, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Use a sigla com 2 letras maiúsculas (ex: SP)', regex='^[A-Z]{2}$')], verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, help_text='8 dígitos sem hífen (ex: 12345678)', max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8}$', 'Use 8 dígitos sem hífen')], verbose_name='CEP')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['state', 'city', 'street'],
                'indexes': [models.Index(fields=['state'], name='addresses_a_state_597299_idx'), models.Index(fields=['city'], name='addresses_a_city_5be026_idx'), models.Index(fields=['zip_code'], name='addresses_a_zip_cod_ef507c_idx'), models.Index(fields=['content_type', 'object_id'], name='addresses_a_content_563811_idx')],
            },
        ),
    ]
