# Generated by Django 5.2 on 2025-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, help_text="Número ou 'SN' se não houver", max_length=10, null=True, verbose_name='Número'),
        ),
    ]
