# Generated by Django 5.2 on 2025-04-30 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, help_text='8 dígitos sem hífen (ex: 12345678)', max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8}$', 'Use 8 dígitos sem hífen')], verbose_name='CEP'),
        ),
    ]
