# Generated by Django 5.2 on 2025-04-20 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNPJ', 'CNPJ (Pessoa Jurídica)'), ('CPF', 'CPF (Profissional)'), ('NI', 'Sem documento (Informal)')], default='CNPJ', max_length=4, verbose_name='Tipo de Documento')),
                ('document', models.CharField(blank=True, help_text='Digite apenas números (14 dígitos para CNPJ, 11 para CPF)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ (14 dígitos) ou CPF (11 dígitos)', regex='^\\d{11,14}$')], verbose_name='CNPJ/CPF')),
                ('is_informal', models.BooleanField(default=False, help_text='Marque para fornecedores sem documento formal', verbose_name='Cadastro Informal')),
                ('legal_name', models.CharField(blank=True, help_text='Nome completo/Razão social (obrigatório para CNPJ)', max_length=100, verbose_name='Razão Social*')),
                ('trade_name', models.CharField(blank=True, max_length=80, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(blank=True, help_text='E-mail válido para contato', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, help_text='Telefone com DDD (apenas números)', max_length=11, validators=[django.core.validators.RegexValidator(message='Use DDD + número (10 ou 11 dígitos)', regex='^\\d{10,11}$')], verbose_name='Telefone*')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['document'], name='suppliers_s_documen_f70606_idx'), models.Index(fields=['legal_name'], name='suppliers_s_legal_n_9de6b0_idx')],
            },
        ),
    ]
