# Generated by Django 5.2 on 2025-05-04 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('IND', 'Pessoa Física'), ('CORP', 'Pessoa Jurídica')], default='CORP', max_length=6, verbose_name='Tipo de Fornecedor')),
                ('corporate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia')),
                ('tax_id', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('state_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('bank_agency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-registration_date', 'trade_name'],
                'indexes': [models.Index(fields=['corporate_name'], name='suppliers_s_corpora_000148_idx'), models.Index(fields=['tax_id'], name='suppliers_s_tax_id_b5d5af_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
    ]
