# Generated by Django 5.2 on 2025-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-registration_date', 'full_name'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='suppliers_s_corpora_000148_idx',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='corporate_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social / Nome Completo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia / Apelido'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['full_name'], name='suppliers_s_full_na_d36d10_idx'),
        ),
    ]
