# Generated by Django 5.2 on 2025-04-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Nome completo/Razão social', max_length=100, null=True, verbose_name='Razão Social'),
        ),
    ]
