# Generated by Django 5.2 on 2025-05-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(default='Nome nao especificado', max_length=100, verbose_name='Razão Social / Nome Completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(default='', max_length=18, unique=True, verbose_name='CNPJ/CPF'),
            preserve_default=False,
        ),
    ]
