# Generated by Django 5.2 on 2025-04-20 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_legal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail válido para contato', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone com DDD (apenas números)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Use DDD + número (10 ou 11 dígitos)', regex='^\\d{10,11}$')], verbose_name='Telefone'),
        ),
    ]
