# Generated by Django 5.2 on 2025-04-20 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_email_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='document',
            field=models.CharField(blank=True, help_text='Digite apenas números (14 dígitos para CNPJ, 11 para CPF)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11,14}$', 'CNPJ (14 dígitos) ou CPF (11 dígitos)')], verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='legal_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Use DDD + número (10 ou 11 dígitos)')], verbose_name='Telefone'),
        ),
    ]
