# Generated by Django 5.2 on 2025-05-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(default='', help_text='Nome completo (PF) ou Razão Social (PJ)', max_length=100, verbose_name='Razão Social / Nome Completo'),
        ),
    ]
