# Generated by Django 5.2 on 2025-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='selected_theme',
            field=models.CharField(blank=True, choices=[('theme-blue-gray', 'Padrão (Azul e Cinza)'), ('theme-green-gray', 'Verde e Cinza'), ('theme-brown-sand', 'Marrom e Areia'), ('theme-urple-gray', 'Roxo e Cinza')], default='theme-blue-gray', max_length=50, verbose_name='Tema Preferido'),
        ),
    ]
