# Generated by Django 5.2 on 2025-05-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_selected_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='selected_theme',
            field=models.CharField(blank=True, choices=[('theme-blue-gray', 'Azul (Padrão)'), ('theme-green-gray', 'Verde'), ('theme-brown-sand', 'Marrom'), ('theme-purple-gray', 'Roxo')], default='theme-blue-gray', max_length=50, verbose_name='Tema Preferido'),
        ),
    ]
